In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

d3_trabalhado = pd.read_csv("d3_trabalhado.csv", sep=",")

In [41]:
d3_trabalhado.isna().sum().value_counts()

0    67
Name: count, dtype: int64

# Math

## Seleção de Features com target de regressão

In [42]:
X = d3_trabalhado.drop(['G3_x'], axis=1)
y = d3_trabalhado['G3_x']

In [43]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

f_regression = SelectKBest(score_func=f_regression, k=8)

In [44]:
fit = f_regression.fit(X, y)

In [45]:
features = fit.transform(X)

In [46]:
print(features)

[[ 0  1  5 ...  0 11 11]
 [ 0  1  5 ...  9 11 11]
 [ 3  1  7 ... 12 13 12]
 ...
 [ 1  1  6 ... 11 12  9]
 [ 0  1 14 ... 10 10 10]
 [ 0  1 11 ... 10 11 11]]


In [48]:
cols = fit.get_support(indices=True)
d3.iloc[:, cols]

failures_x  higher_x  G1_x  G2_x  activities_y  absences_y  G1_y  G2_y
0             0         1     5     6             0           4     0    11
1             0         1     5     5             0           2     9    11
2             3         1     7     8             0           6    12    13
3             0         1    15    14             1           0    14    14
4             0         1     6    10             0           0    11    13
..          ...       ...   ...   ...           ...         ...   ...   ...
377           0         1     7     9             0           4    15    15
378           1         1     6     5             1           3     7     8
379           1         1     6     5             1           6    11    12
380           0         1    14    16             0           6    10    10
381           0         1    11    12             0           4    10    11

[382 rows x 8 columns]

## Aplicando o recursive feature elimination - RFE

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression(solver='saga', max_iter=5000)
rfe = RFE(model, n_features_to_select=6, step=2)

In [50]:
fit = rfe.fit(X,y)

In [51]:
print("Número de features: {}".format(fit.n_features_))

Número de features: 6


In [53]:
cols = fit.get_support(indices=True)
d3.iloc[:, cols]

age  failures_x  G1_x  G2_x  paid_y  Mjob_other
0     18           0     5     6       0           0
1     17           0     5     5       0           0
2     15           3     7     8       0           0
3     15           0    15    14       0           0
4     16           0     6    10       0           1
..   ...         ...   ...   ...     ...         ...
377   18           0     7     9       0           0
378   18           1     6     5       0           1
379   18           1     6     5       0           1
380   17           0    14    16       0           0
381   18           0    11    12       0           0

[382 rows x 6 columns]